[package]
name = "tokio-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
crossbeam = "0.8.4"
frame = "0.0.0"
futures = "0.3.31"
mini-redis = "0.4.1"
tokio = { version = "1.42.0", features = ["full"] }
